### ISSUE TITLE
Add ability to specify whether you want special characters or digits

### ISSUE THREAD

**Issue by shaunroselt** [Praveensenpai/password-generator#1]
Add another parameter to your `password_generator` function where you can specify whether you want to include special characters or digits in the password or not.

Currently the parameters are just for specifiying `size` and nothing else.

**Comment by Praveensenpai** [comment]
Sure, I can modify the password_generator function to include an optional parameter for specifying whether to include special characters or digits in the password or not.

But I never thought someone will see my repo 🧐

**Comment by Praveensenpai** [comment]
resolved the issue

thanks for your feedback.

**Comment by shaunroselt** [comment]
Awesome!
