### ISSUE TITLE
Make a GUI for the app

### ISSUE THREAD

**Issue by shaunroselt** [Praveensenpai/password-generator#2]
How do you feel about making a GUI for the password generator?

Have you done any GUI programming in Python?

I'd be keen to collaborate on a GUI. Make something basic and do a pull request for it.

**Comment by Praveensenpai** [comment]
sure I'll do it and you can help me by contributing it later

**Comment by shaunroselt** [comment]
> sure I'll do it and you can help me by contributing it later

Do you want to do the first GUI commit?

What GUI library do you want to use?

**Comment by Praveensenpai** [comment]
probably flet

**Comment by shaunroselt** [comment]
This? 

https://flet.dev/

**Comment by Praveensenpai** [comment]
yes

**Comment by Praveensenpai** [comment]
added the gui check out and add a pull request if u want to add something

**Comment by shaunroselt** [comment]
You should add a screenshot of the GUI to the readme file actually

**Comment by Praveensenpai** [comment]
you can add it and do pull request

**Comment by Praveensenpai** [comment]
> You should add a screenshot of the GUI to the readme file actually

you can add it and do pull request

**Comment by Praveensenpai** [comment]
> You should add a screenshot of the GUI to the readme file actually

added a single screenshot.

**Comment by shaunroselt** [comment]
Looking good 😁
